default:
  suites:
    # ALL THE THINGS - for development
    all:
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
      paths:
        - %paths.base%/features
        - %paths.base%/../../includes/features
    default:
      filters:
        tags: "safe&&~destructive&&~content"
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
      paths:
        - %paths.base%/features
        - %paths.base%/../../includes/features

    # --- Lifecyle Phases Suites ---
    # Tests that are meant for development sites and can have config changes.
    dev:
      filters:
        tags: 'safe,deploy,dev&&~live&&~launch'
        #'safe,deploy,dev'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
      paths:
        - %paths.base%/features
        - %paths.base%/../../includes/features
    # A freshly deployed site/product that needs to be confirmed
    deploy:
      filters:
        tags: 'safe,deploy&&~destructive&&~content&&~launch&&~live'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
      paths:
        - %paths.base%/features
        - %paths.base%/../../includes/features
    # Is the site ready for launch? Any placeholder content?
    launch:
      filters:
        tags: 'safe,launch&&~destructive&&~content&&~deploy&&~dev&&~live'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
      paths:
        - %paths.base%/features
        - %paths.base%/../../includes/features
    # Tests that are safe for production and live sites.
    live:
      filters:
        tags: 'live,safe,prod&&~content&&~destructive&&~deploy&&~dev&&~live'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
      paths:
        - %paths.base%/features
        - %paths.base%/../../includes/features

    # --- Hosting Suites ---
    # Tests for Stanford Sites hosting.
    sites:
      filters:
        tags: 'safe,sites&&~content&&~destructive'
        #@Shea what do you think here?
        #tags: 'dev&&~live&&~prod'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
      paths:
        - %paths.base%/features
        - %paths.base%/../../includes/features
    # Tests for Anchorage hosting.
    anchorage:
      filters:
        tags: 'safe,anchorage&&~content&&~destructive'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
      paths:
        - %paths.base%/features
        - %paths.base%/../../includes/features
    # Tests for local hosting.
    local:
      filters:
        tags: 'safe,local&&~content&&~destructive'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
      paths:
        - %paths.base%/features
        - %paths.base%/../../includes/features
    # -- Authentication Suites ---
    # Tests for SAML authentication.
    saml:
      filters:
        tags: 'safe,saml&&~content&&~destructive'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
      paths:
        - %paths.base%/features
        - %paths.base%/../../includes/features
    # Tests for webauth authentication.
    webauth:
      filters:
        tags: 'safe,webauth&&~content&&~destructive'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
      paths:
        - %paths.base%/features
        - %paths.base%/../../includes/features
    # Tests for Drupal authentication.
    drupal:
      filters:
        tags: 'safe,drupal&&~content&&~destructive'
        #@Shea what do you think here?
        #tags: 'deploy&&~dev&&~destructive&&~content'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
      paths:
        - %paths.base%/features
        - %paths.base%/../../includes/features

    # --- Additonal Suites ---
    # Only content creating related tasks
    content:
      filters:
        tags: 'content'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
      paths:
        - %paths.base%/features
        - %paths.base%/../../includes/features
    # For tests that are specific to the site it is testing.
    site:
      filters:
        tags: 'site'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
      paths:
        - %paths.base%/features
        - %paths.base%/../../includes/features
    # Only contrib module tests that are safe.
    contrib:
      filters:
        tags: 'contrib&&~dev&&~destructive'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
      paths:
        - %paths.base%/features
        - %paths.base%/../../includes/features
        # Any contrib module even if it is destructive.
    contrib-dev:
      filters:
        tags: 'contrib'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
      paths:
        - %paths.base%/features
        - %paths.base%/../../includes/features
    # Only stanford module tests.
    stanford:
      filters:
        tags: 'stanford&&~dev&&~destructive'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
      paths:
        - %paths.base%/features
        - %paths.base%/../../includes/features
