default:
  suites:
    default:
      filters:
        tags: "~dev,~destructive"
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
    # Tests that are safe for production and live sites.
    live:
      filters:
        tags: 'live,safe,prod,~content'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
    # Tests that are meant for development sites and can have config changes.
    dev:
      filters:
        tags: '~contrib'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
    # A freshly deployed site/product that needs to be confirmed
    deploy:
      filters:
        tags: 'deploy,~dev,~destructive,~content,~site'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
    # Only content creating related tasks
    content:
      filters:
        tags: 'content'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
    # For tests that are specific to the site it is testing.
    site:
      filters:
        tags: 'site'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
    # Only contrib module tests that are safe.
    contrib:
      filters:
        tags: 'contrib,~dev,~destructive'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
        # Any contrib module even if it is destructive.
    contrib-dev:
      filters:
        tags: 'contrib'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext
    # Only stanford module tests.
    stanford:
      filters:
        tags: 'stanford,~dev,~destructive'
      contexts:
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\MarkupContext
        - Drupal\DrupalExtension\Context\DrushContext
        - Drupal\DrupalExtension\Context\BatchContext
        - FeatureContext
        - SWSFeatureContext
        - SWSMinkContext
        - SWSDrupalContext

